services:
        -       url: "http://www.google.com"
                first_admin: Mateusz Bieganski
                second_admin: Kamil Mykitiuk
                frequency: 10
                allowed_response_time: 1

        -       url: http://www.github.com:21314
                first_admin: Mateusz Bieganski
                second_admin: Kamil Mykitiuk
                frequency: 10
                allowed_response_time: 1
