
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
  selector:
    app: admin-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: admin-server
  name: admin-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
      name: admin-server
    spec:
      terminationGracePeriodSeconds: 60 # Max wait time for jobs to be finished, then force kill the pod.
      containers:
      - image: eu.gcr.io/kubernetes-labs-293308/admin-server
        name: dkron
        volumeMounts:
        - name: secret-config
          mountPath: /secret
        env:
        - name: ALERTING_SECRET_PATH
          value: /secret/secret.yaml
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          periodSeconds: 30
          failureThreshold: 3
          initialDelaySeconds: 120 # Sometimes it takes a lot to rejoin node to a cluster. Pausing there in case we do rolling pod update.
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          periodSeconds: 30
          failureThreshold: 3
          initialDelaySeconds: 120
      volumes:
      - name: secret-config
        configMap:
          name: secret-config
