kind: ConfigMap
apiVersion: v1
metadata:
  name: dkron-worker
data:
  dkron.yml: |-
    retry-join: ["provider=k8s label_selector=\"app=dkron-server\""]
    SerfReconnectTimeout: 5s
    tags:
      worker: crawler
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: db-config
data:
  services.yaml: |-
    - url: "http://www.google.com"
      first_admin: Mateusz Bieganski
      second_admin: Kamil Mykitiuk
      frequency: 10
      alerting_window: 3
      allowed_response_time: 1
    - url: http://www.github.com:2232  # this one for tests purpose will be incident free
      first_admin: Mateusz Bieganski
      second_admin: Kamil Mykitiuk
      frequency: 10
      alerting_window: 4
      allowed_response_time: 1
  admins.yaml: |-
    - name: Mateusz Bieganski
      email: k.mykitiuk@gmail.com
    - name: Kamil Mykitiuk
      email: k.mykitiuk@gmail.com
