apiVersion: v1
kind: Service
metadata:
  name: dkron-worker
  labels:
    app: dkron-worker
spec:
  publishNotReadyAddresses: true
  ports:
  - name: web
    port: 80
  selector:
    app: dkron-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: dkron-worker
  name: dkron-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dkron-worker
  template:
    metadata:
      labels:
        app: dkron-worker
      name: dkron-worker
    spec:
      containers:
      - args:
        - agent --config /opt/local/dkron/config/dkron.yml
        volumeMounts:
        - name: dkron-worker
          mountPath: /opt/local/dkron/config
        - name: secret-config
          mountPath: /secret
        image: eu.gcr.io/kubernetes-labs-293308/worker
        name: dkron
        env:
        - name: ALERTING_SECRET_PATH
          value: /secret/secret.yaml
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 8946
          name: rpc
          protocol: TCP
        - containerPort: 6868
          name: raft
          protocol: TCP
      #serviceAccount: dkron
      terminationGracePeriodSeconds: 60 # Max wait time for jobs to be finished, then force kill the pod.
      volumes:
      - name: dkron-worker
        configMap:
          name: dkron-worker
      - name: secret-config
        configMap:
          name: secret-config
