kind: ConfigMap
apiVersion: v1
metadata:
  name: dkron-worker
data:
  dkron.yml: |-
    retry-join: ["provider=k8s label_selector=\"app=dkron-server\""]
    SerfReconnectTimeout: 5s
    tags:
      worker: crawler
