apiVersion: apps/v1
kind: Deployment
metadata:
  name: primer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primer
  template:
    metadata:
      labels:
        app: primer
      name: dkron-worker
    spec:
      containers:
      - image: eu.gcr.io/kubernetes-labs-293308/primer
        name: primer
        volumeMounts:
        - name: db-config
          mountPath: /db-config
        - name: secret-config
          mountPath: /secret
        env:
        - name: ALERTING_SECRET_PATH
          value: /secret/secret.yaml
      volumes:
      - name: db-config
        configMap:
          name: db-config
      - name: secret-config
        configMap:
          name: secret-config
