apiVersion: v1
kind: ServiceAccount
metadata:
  name: dkron-server-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dkron-server-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "patch", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dkron-server-role
subjects:
  - kind: ServiceAccount
    name: dkron-server-account
    namespace: default
roleRef:
  kind: Role
  name: dkron-server-role
  apiGroup: rbac.authorization.k8s.io
