kind: ConfigMap
apiVersion: v1
metadata:
  name: secret-config
data:
  secret.yaml: |-
    db_user: <user>
    db_password: <password>
    db_name: irio
    debug: true
    dkron_server: http://dkron-server:8080
    services: /db-config/services.yaml
    admins: /db-config/admins.yaml
    incidents: /db-config/incidents.yaml
